### ISSUE TITLE
Examples of feature set

### ISSUE THREAD

**Issue by ChristopherRabotin** [kchmck/rust-modem#1]
Hi there,
I'm not sure this project is still maintained, but I was wondering whether you could provide a feature set as to what is available, and examples on how to use what's available?
Thanks.

**Comment by kchmck** [comment]
Hey @ChristopherRabotin, this was pretty much a toy project for me and isn't production ready or anything like that. I think the main feature is it can take a stream of bits and generate the constellation points for a bunch of different digital modulations (listed [here](https://github.com/kchmck/rust-modem/blob/master/src/bin/modulate.rs#L75)) and modulate that onto a carrier. It doesn't do any sort of pulse shape filtering or demodulation at this point, though. 

From the command line, you can use it like

```
$ echo "0000
0001
0010
0011
0100
0101
0110
0111
1000
" >test.bits
$ ./target/release/modulate -m mfsk -r 240000 -b 32 -c 1000 <test.bits >sig.f32le
```
